[package]
name = "most-urls"
version = "0.1.0"
edition = "2024"

[dependencies]
nanoserde = { version = "0.2.1", default-features = false, features = ["std", "json"] }
polars = { version = "0.48.1", features = ["lazy"] }
# urlencoding = "2.1.3"

[profile.release]
# magic incantations to produce speedier release builds
strip = "symbols"
lto = true
codegen-units = 1
